### PR TITLE
Feature/x documentation url

### PR DESCRIPTION
**Pull request by dok**
What do you guys think about this flow?

1. End-user makes request
2. `readme-node` generates logId and URL
  - E.g. "https://dash.readme.io/logs/[GENERATED ID]" (we would need to create a new route)
3. End-user goes to said URL
4. End-user is routed to the hub of the associated project ([HUB_URL]/logs/:id)

Thoughts @mjcuva?

### CODE REVIEW

**Comment by mjcuva** [comment]
I want to revisit this now!

I think this looks great, the only change I would make is that I don't think we can have dash.readme.io be the url (since we are in people's api responses it needs to be white labeled). I think maybe the best way to do this is have a configuration option to provide the docs url (this way we don't need to make a call to readme which can be slow or down). For now if no url is provided we can fallback to dash.readme.io (logs.readme.io to keep everything on the hub).

Since people will just copy and paste any code sample we send them the initial code sample for setting this up can just have their custom domain in it!

**Comment by gkoberger** [comment]
I made a change to just surface the log ID for now. We should add the full URL, but alas...

It doesn't seem to actually save the custom-made `id`, though. So we need to fix this!

**Comment by erunion** [comment]
We're consolidating our Metrics SDK repos down to help build up a unified testing framework so I'll pull this work into https://github.com/readmeio/metrics-sdks.

**Comment by gkoberger** [comment]
Update! Evidently this should now be a uuid, not `ObjectId()`, and I also assume it's not set at `_id`? So, in theory I still like this change but just wanted to ⚠️ warn not to merge or anything!

**Comment by erunion** [comment]
Cherry picked all these commits over to https://github.com/readmeio/metrics-sdks/pull/6 and will wrap this up there.

**Pull request closed without merging**
